### PR TITLE
[FIX] added a timeout of 30 seconds by default

### PR DESCRIPTION
**Pull request by yo2x**

### CODE REVIEW

**Comment by gosuto-inzasheru** [comment]
I can't find this parameter in the [docs](https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#klinecandlestick-data)?

**Comment by yo2x** [comment]
@jorijnsmit check this out
https://requests.readthedocs.io/en/master/user/quickstart/#timeouts

**Comment by gosuto-inzasheru** [comment]
Ah I see now, it is part of the `requests` API. I guess it doesn't hurt to make it 30 seconds instead of the default `None` (wait till connection hangs).

Do you get a lot of connection problems? I never gave it much attention since it all seems to work fine for me.

**Comment by yo2x** [comment]
not really, but the other day we had a power cut and my router went off, since my pc was still up it hung, that's how i started testing requests exceptions.
BTW, 1 second is enough, but 30 gives it more sense

**Pull request merged**
